#!/bin/bash

# Escolher quantum
QOPT=$(zenity --list --radiolist \
  --title="Quantum do PipeWire" \
  --text="Escolha o quantum (tamanho do buffer):" \
  --column="Selecionado" --column="Valor" \
  --height=412 \
  FALSE "64" \
  TRUE "128" \
  FALSE "256" \
  FALSE "512" \
  FALSE "custom") || exit

if [[ "$QOPT" == "custom" ]]; then
  QOPT=$(zenity --entry --title="Quantum personalizado" \
    --text="Digite o quantum (ex: 98):" \
    --entry-text="128") || exit
fi

# Escolher sample rate
ROPT=$(zenity --list --radiolist \
  --title="Sample Rate do PipeWire" \
  --text="Escolha a taxa de amostragem:" \
  --column="Selecionado" --column="Valor" \
  --height=370 \
  TRUE "44100" \
  FALSE "48000" \
  FALSE "88200" \
  FALSE "96000") || exit

if [[ "$ROPT" == "custom" ]]; then
  ROPT=$(zenity --entry --title="Sample rate personalizado" \
    --text="Digite a taxa de amostragem (ex: 44100):" \
    --entry-text="44100") || exit
fi

# Confirmar aplicação
zenity --question \
  --title="Aplicar configuração" \
  --text="Quantum: $QOPT\nSample rate: $ROPT\n\nDeseja aplicar agora?" || exit

# Salvar no /etc/profile.d usando pkexec
#printf "export PIPEWIRE_LATENCY=\"$QOPT/$ROPT\"" | pkexec tee /etc/profile.d/pwjack.sh

# Aplicar imediatamente no usuário atual
#pw-metadata -n settings 0 clock.force-rate "$ROPT"
#pw-metadata -n settings 0 clock.force-quantum "$QOPT"

mkdir -p "$HOME"/.config/pipewire/pipewire.conf.d
export QOPT=$QOPT
export ROPT=$ROPT
curl -sL https://rauldipeas.com.br/uds/settings/99-custom.conf | envsubst | tee "$HOME"/.config/pipewire/pipewire.conf.d/99-custom.conf >/dev/null

systemctl --user restart pipewire pipewire-pulse

zenity --info --text="Configuração salva e aplicada imediatamente."